/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mainframe;

import java.awt.Color;
import org.mainframe.common.model.CourseSectionModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

import net.proteanit.sql.DbUtils;

import org.mainframe.common.model.DBUtil;
import org.mainframe.common.bean.CourseSectionBean;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author V
 */
public class CourseSectionFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserJInternalFrame
     */
    public CourseSectionFrame() {
        initComponents();
        courseSectionMsgLabel.setVisible(false);        
       getContentPane().setBackground(Color.WHITE);
        try{
            String sql = " Select DISTINCT CourseCode From Course";
            Connection con = DBUtil.getDataSource().getConnection();
		PreparedStatement ps =	con.prepareStatement(sql);
		ResultSet rs = ps.executeQuery();
              
                while(rs.next()){
                   course.addItem(rs.getString(1));
                }
               
                rs.close();
                ps.close();
                con.close();
        }catch(Exception exp){
            JOptionPane.showMessageDialog(this, "exception raised"+exp);
        }
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSectionNumber = new javax.swing.JLabel();
        lblCourse = new javax.swing.JLabel();
        sectionNumber = new javax.swing.JTextField();
        addCourseSectionButton = new javax.swing.JButton();
        updateCourseSectionButton = new javax.swing.JButton();
        deleteCourseSectionButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseSectionDataTable = new javax.swing.JTable();
        courseSectionMsgLabel = new javax.swing.JLabel();
        lblFaculty = new javax.swing.JLabel();
        faculty = new javax.swing.JTextField();
        cancelCourseSectionButton = new javax.swing.JButton();
        course = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CourseSectionFrame");

        lblSectionNumber.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblSectionNumber.setText("Section Number");

        lblCourse.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblCourse.setText("Course");

        sectionNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionNumberActionPerformed(evt);
            }
        });

        addCourseSectionButton.setBackground(new java.awt.Color(102, 255, 255));
        addCourseSectionButton.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        addCourseSectionButton.setText("Add");
        addCourseSectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseSectionButtonActionPerformed(evt);
            }
        });

        updateCourseSectionButton.setBackground(new java.awt.Color(102, 255, 255));
        updateCourseSectionButton.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        updateCourseSectionButton.setText("Update");
        updateCourseSectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCourseSectionButtonActionPerformed(evt);
            }
        });

        deleteCourseSectionButton.setBackground(new java.awt.Color(102, 255, 255));
        deleteCourseSectionButton.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        deleteCourseSectionButton.setText("Delete");
        deleteCourseSectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCourseSectionButtonActionPerformed(evt);
            }
        });

        courseSectionDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        courseSectionDataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courseSectionDataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(courseSectionDataTable);

        courseSectionMsgLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        courseSectionMsgLabel.setForeground(new java.awt.Color(255, 0, 0));

        lblFaculty.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblFaculty.setText("Faculty");

        faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyActionPerformed(evt);
            }
        });

        cancelCourseSectionButton.setBackground(new java.awt.Color(102, 255, 255));
        cancelCourseSectionButton.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        cancelCourseSectionButton.setText("Reset");
        cancelCourseSectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelCourseSectionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addCourseSectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateCourseSectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteCourseSectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelCourseSectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSectionNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sectionNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(courseSectionMsgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(courseSectionMsgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSectionNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sectionNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(faculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCourseSectionButton)
                            .addComponent(updateCourseSectionButton)
                            .addComponent(deleteCourseSectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelCourseSectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(388, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCourseSectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseSectionButtonActionPerformed
        // TODO add your handling code here:
       try{
           
           if(sectionNumber.getText() !=null && !sectionNumber.getText().trim().equals("") ){    
                       CourseSectionModel courseSectionModel = new CourseSectionModel();
               if(!courseSectionModel.isCourseSectionExist(sectionNumber.getText())){
                CourseSectionBean courseSectionBean = new CourseSectionBean();
                courseSectionBean.setSectionNumber(sectionNumber.getText());
                courseSectionBean.setCourse(course.getSelectedItem().toString()); 
              
                courseSectionBean.setFaculty(faculty.getText());
                
                
                courseSectionModel.addCourseSection(courseSectionBean);
           
           courseSectionMsgLabel.setText("Registration is Successfull.");           
           loadDataIntoJTable();                      
            sectionNumber.setText("");
//            course.setText("");                  
            faculty.setText("");
          
            
               }else{
                   courseSectionMsgLabel.setText("Section Number is already exist in the System.");
               }
           }else{
               courseSectionMsgLabel.setText("Section Number Should not be Empty.");
           }
       }catch(Exception exp){
           JOptionPane.showMessageDialog(null, exp);
       } 
        
    }//GEN-LAST:event_addCourseSectionButtonActionPerformed

    private void courseSectionDataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseSectionDataTableMouseClicked
        // TODO add your handling code here:
       try{
          int rowIndex = courseSectionDataTable.getSelectedRow();
          
           sectionNumber.setText(courseSectionDataTable.getValueAt(rowIndex, 0).toString());
           course.setSelectedItem(courseSectionDataTable.getValueAt(rowIndex, 1).toString());    
           faculty.setText(courseSectionDataTable.getValueAt(rowIndex, 2).toString());          
                 
          
       }catch(Exception exp){
          // JOptionPane.showMessageDialog(null, exp);
       }
    }//GEN-LAST:event_courseSectionDataTableMouseClicked

    private void updateCourseSectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCourseSectionButtonActionPerformed
        // TODO add your handling code here:
          try{
           
           if(sectionNumber.getText() !=null && !sectionNumber.getText().trim().equals("") ){    
                       CourseSectionModel courseSectionModel = new CourseSectionModel();
               if(courseSectionModel.isCourseSectionExist(sectionNumber.getText())){
                CourseSectionBean courseSectionBean = new CourseSectionBean();
                courseSectionBean.setSectionNumber(sectionNumber.getText());
                courseSectionBean.setCourse(course.getSelectedItem().toString()); 
                 courseSectionBean.setFaculty(faculty.getText());
                
                
                courseSectionModel.updateCourseBean(courseSectionBean);
           
           courseSectionMsgLabel.setText("Updation is Successfull.");           
           loadDataIntoJTable();                      
            
            
               }else{
                   courseSectionMsgLabel.setText("Section Number is not exist in the System.");
               }
           }else{
               courseSectionMsgLabel.setText("Section Number Should not be Empty.");
           }
       }catch(Exception exp){
           JOptionPane.showMessageDialog(null, exp);
       } 
    }//GEN-LAST:event_updateCourseSectionButtonActionPerformed

    private void deleteCourseSectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCourseSectionButtonActionPerformed
        // TODO add your handling code here:
          try{
             CourseSectionModel courseSectionModel = new CourseSectionModel();
         boolean flag = courseSectionModel.isCourseSectionExist(sectionNumber.getText());
           if(flag){
             courseSectionModel.deleteCourseSection(sectionNumber.getText());               
               loadDataIntoJTable();
                
            courseSectionMsgLabel.setText("Deletion is Successfull.");
            sectionNumber.setText("");
//            course.setText("");                    
            faculty.setText("");
          
            
           }else{
           courseSectionMsgLabel.setText(" Please enter valid Section Number .");
           }
       }catch(Exception exp){
           JOptionPane.showMessageDialog(null, exp);
       } 
    }//GEN-LAST:event_deleteCourseSectionButtonActionPerformed

    private void sectionNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sectionNumberActionPerformed

    private void cancelCourseSectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelCourseSectionButtonActionPerformed
        // TODO add your handling code here:
            sectionNumber.setText("");
//            course.setText("");                       
            faculty.setText("");
          
           
    }//GEN-LAST:event_cancelCourseSectionButtonActionPerformed

    private void facultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyActionPerformed

    public JTable getSchoolDataTable(){
        return courseSectionDataTable;
    }
    
    public JLabel getSchoolMsgLabel(){
        return courseSectionMsgLabel;
    }
    
    public void loadDataIntoJTable() throws Exception{
    	
    	Connection con = DBUtil.getDataSource().getConnection();	
        String selectSchoolsSql = "Select * From CourseSection";
     	PreparedStatement ps =	con.prepareStatement(selectSchoolsSql);
     	ResultSet rs = ps.executeQuery();		
        courseSectionDataTable.setModel(DbUtils.resultSetToTableModel(rs));
                rs.close();
                ps.close();
                con.close();
    }

    public JButton getAddCourseSectionButton() {
        return addCourseSectionButton;
    }

    public JButton getCancelCourseSectionButton() {
        return cancelCourseSectionButton;
    }

    public JComboBox<String> getCourse() {
        return course;
    }

   

    public JTable getCourseSectionDataTable() {
        return courseSectionDataTable;
    }

    public JLabel getCourseSectionMsgLabel() {
        return courseSectionMsgLabel;
    }

    public JButton getDeleteCourseSectionButton() {
        return deleteCourseSectionButton;
    }

    public JTextField getFaculty() {
        return faculty;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JLabel getLblCourse() {
        return lblCourse;
    }

    public JLabel getLblFaculty() {
        return lblFaculty;
    }

    public JLabel getLblSectionNumber() {
        return lblSectionNumber;
    }

   

    public JTextField getSectionNumber() {
        return sectionNumber;
    }

   

    public JButton getUpdateCourseSectionButton() {
        return updateCourseSectionButton;
    }

    
    
   
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCourseSectionButton;
    private javax.swing.JButton cancelCourseSectionButton;
    private javax.swing.JComboBox<String> course;
    private javax.swing.JTable courseSectionDataTable;
    private javax.swing.JLabel courseSectionMsgLabel;
    private javax.swing.JButton deleteCourseSectionButton;
    private javax.swing.JTextField faculty;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblFaculty;
    private javax.swing.JLabel lblSectionNumber;
    private javax.swing.JTextField sectionNumber;
    private javax.swing.JButton updateCourseSectionButton;
    // End of variables declaration//GEN-END:variables
}
