/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mainframe;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

import net.proteanit.sql.DbUtils;

import org.mainframe.common.model.DBUtil;
import org.mainframe.common.model.FacultyModel;
import org.mainframe.common.model.GradSchoolModel;
import org.mainframe.common.bean.FacultyBean;
import org.mainframe.common.bean.SchoolBean;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author V
 */
public class FacultyFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserJInternalFrame
     */
    public FacultyFrame() {
        initComponents();
        facultyMsgLabel.setVisible(false);
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        addFacultyButton = new javax.swing.JButton();
        updateFacultyButton = new javax.swing.JButton();
        deleteFacultyButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        facutlyDataTable = new javax.swing.JTable();
        facultyMsgLabel = new javax.swing.JLabel();
        gradSchool = new javax.swing.JTextField();
        lblDegree = new javax.swing.JLabel();
        lblGradSchool = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblDaysToTeach = new javax.swing.JLabel();
        lblMaxLoadFall = new javax.swing.JLabel();
        lblMaxLoadSpring = new javax.swing.JLabel();
        lblMaxLoadSummer = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        degree = new javax.swing.JTextField();
        titleTextField = new javax.swing.JTextField();
        daysToTeach = new javax.swing.JTextField();
        maxLoadFall = new javax.swing.JTextField();
        maxLoadSpring = new javax.swing.JTextField();
        maxLoadSummer = new javax.swing.JTextField();
        cancelFacultyButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("FacultyFrame");

        lblFirstName.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblFirstName.setText("FirstName");

        lblLastName.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblLastName.setText("LastName");

        addFacultyButton.setBackground(new java.awt.Color(102, 255, 255));
        addFacultyButton.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        addFacultyButton.setText("Add");
        addFacultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFacultyButtonActionPerformed(evt);
            }
        });

        updateFacultyButton.setBackground(new java.awt.Color(102, 255, 255));
        updateFacultyButton.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        updateFacultyButton.setText("Update");
        updateFacultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFacultyButtonActionPerformed(evt);
            }
        });

        deleteFacultyButton.setBackground(new java.awt.Color(102, 255, 255));
        deleteFacultyButton.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        deleteFacultyButton.setText("Delete");
        deleteFacultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFacultyButtonActionPerformed(evt);
            }
        });

        facutlyDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        facutlyDataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facutlyDataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(facutlyDataTable);

        facultyMsgLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        facultyMsgLabel.setForeground(new java.awt.Color(255, 0, 0));

        lblDegree.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblDegree.setText("Degree");

        lblGradSchool.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblGradSchool.setText("GradSchool");

        lblTitle.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblTitle.setText("Title");

        lblDaysToTeach.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblDaysToTeach.setText("DaysToTeach");

        lblMaxLoadFall.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblMaxLoadFall.setText("MaxLoadFall");

        lblMaxLoadSpring.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblMaxLoadSpring.setText("MaxLoadSpring");

        lblMaxLoadSummer.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblMaxLoadSummer.setText("MaxLoadSummer");

        maxLoadFall.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        cancelFacultyButton.setBackground(new java.awt.Color(102, 255, 255));
        cancelFacultyButton.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        cancelFacultyButton.setText("Reset");
        cancelFacultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelFacultyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblMaxLoadFall, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblMaxLoadSummer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblMaxLoadSpring, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maxLoadFall, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maxLoadSpring, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maxLoadSummer, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addFacultyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateFacultyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteFacultyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelFacultyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblGradSchool, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gradSchool, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblDegree, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(degree, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblDaysToTeach, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(daysToTeach, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(facultyMsgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(facultyMsgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGradSchool, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gradSchool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDegree, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(degree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDaysToTeach, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(daysToTeach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaxLoadFall, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxLoadFall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaxLoadSpring, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxLoadSpring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaxLoadSummer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxLoadSummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFacultyButton)
                    .addComponent(updateFacultyButton)
                    .addComponent(deleteFacultyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelFacultyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFacultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFacultyButtonActionPerformed
        // TODO add your handling code here:
       try{
           
           if(firstName.getText() !=null && !firstName.getText().trim().equals("") && titleTextField.getText()!= null && !titleTextField.getText().trim().equals("")){    
                       
               FacultyBean facultyBean = new FacultyBean();
               facultyBean.setFirstName(firstName.getText());
                facultyBean.setLastName(lastName.getText()); 
                facultyBean.setGradSchool(gradSchool.getText());
                facultyBean.setDaysToTeach(daysToTeach.getText());
                facultyBean.setTitle(titleTextField.getText());
                facultyBean.setDegree(degree.getText());
                facultyBean.setMaxLoadFall(Double.valueOf(maxLoadFall.getText())); 
                facultyBean.setMaxLoadSpring(Double.valueOf(maxLoadSpring.getText()));
                facultyBean.setMaxLoadSummer(Double.valueOf(maxLoadSummer.getText()));                
                new FacultyModel().addFaculty(facultyBean);
           
           facultyMsgLabel.setText("Registration is Successfull.");           
           loadDataIntoJTable();                      
            firstName.setText("");
            lastName.setText("");
            gradSchool.setText("");
            degree.setText("");           
            titleTextField.setText("");
            daysToTeach.setText("");
            maxLoadFall.setText("");
            maxLoadSpring.setText("");
            maxLoadSummer.setText("");
           }else{
               facultyMsgLabel.setText("FirstName and Title Should not be Empty.");
           }
       }catch(Exception exp){
           JOptionPane.showMessageDialog(null, exp);
       } 
        
    }//GEN-LAST:event_addFacultyButtonActionPerformed

    private void facutlyDataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facutlyDataTableMouseClicked
        // TODO add your handling code here:
       try{
          int rowIndex = facutlyDataTable.getSelectedRow();
          
           firstName.setText(facutlyDataTable.getValueAt(rowIndex, 0).toString());
           lastName.setText(facutlyDataTable.getValueAt(rowIndex, 1).toString());          
           gradSchool.setText(facutlyDataTable.getValueAt(rowIndex, 2).toString());          
           degree.setText(facutlyDataTable.getValueAt(rowIndex, 3).toString());          
           titleTextField.setText(facutlyDataTable.getValueAt(rowIndex, 4).toString());          
           daysToTeach.setText(facutlyDataTable.getValueAt(rowIndex, 5).toString());          
           maxLoadFall.setText(facutlyDataTable.getValueAt(rowIndex, 6).toString());          
           maxLoadSpring.setText(facutlyDataTable.getValueAt(rowIndex, 7).toString());          
           maxLoadSummer.setText(facutlyDataTable.getValueAt(rowIndex, 8).toString());          
       }catch(Exception exp){
          // JOptionPane.showMessageDialog(null, exp);
       }
    }//GEN-LAST:event_facutlyDataTableMouseClicked

    private void updateFacultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFacultyButtonActionPerformed
        // TODO add your handling code here:
         try{
           if(new FacultyModel().isFacultyExist(firstName.getText())){                     
               FacultyBean facultyBean = new FacultyBean();
               facultyBean.setFirstName(firstName.getText());
                facultyBean.setLastName(lastName.getText()); 
                facultyBean.setGradSchool(gradSchool.getText());
                facultyBean.setDaysToTeach(daysToTeach.getText());
                facultyBean.setTitle(titleTextField.getText());
                facultyBean.setDegree(degree.getText());
                facultyBean.setMaxLoadFall(Double.valueOf(maxLoadFall.getText())); 
                facultyBean.setMaxLoadSpring(Double.valueOf(maxLoadSpring.getText()));
                facultyBean.setMaxLoadSummer(Double.valueOf(maxLoadSummer.getText()));  
                
                new FacultyModel().updateFaculty(facultyBean);
          loadDataIntoJTable();          
           
           facultyMsgLabel.setText("Updation is Successfull.");
         }else{
                 facultyMsgLabel.setText("Please enter valid Faculty FirstName ");
              }
       }catch(Exception exp){
           JOptionPane.showMessageDialog(null, exp);
       } 
    }//GEN-LAST:event_updateFacultyButtonActionPerformed

    private void deleteFacultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFacultyButtonActionPerformed
        // TODO add your handling code here:
         try{
         boolean flag = new FacultyModel().isFacultyExist(firstName.getText());
           if(flag){
             new FacultyModel().deleteFaculty(firstName.getText());               
               loadDataIntoJTable();
                
                facultyMsgLabel.setText("Deletion is Successfull.");
            firstName.setText("");
            lastName.setText("");
            gradSchool.setText("");
            degree.setText("");           
            titleTextField.setText("");
            daysToTeach.setText("");
            maxLoadFall.setText("");
            maxLoadSpring.setText("");
            maxLoadSummer.setText("");
           }else{
           facultyMsgLabel.setText(" Please enter valid Faculty First Name .");
           }
       }catch(Exception exp){
           JOptionPane.showMessageDialog(null, exp);
       } 
    }//GEN-LAST:event_deleteFacultyButtonActionPerformed

    private void cancelFacultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelFacultyButtonActionPerformed
        // TODO add your handling code here:
        firstName.setText("");
            lastName.setText("");
            gradSchool.setText("");
            degree.setText("");           
            titleTextField.setText("");
            daysToTeach.setText("");
            maxLoadFall.setText("");
            maxLoadSpring.setText("");
            maxLoadSummer.setText("");
    }//GEN-LAST:event_cancelFacultyButtonActionPerformed

    public JTable getSchoolDataTable(){
        return facutlyDataTable;
    }
    
    public JLabel getSchoolMsgLabel(){
        return facultyMsgLabel;
    }
    
    public void loadDataIntoJTable() throws Exception{
    	
    	Connection con = DBUtil.getDataSource().getConnection();	
        String selectSchoolsSql = "Select * From Faculty";
     	PreparedStatement ps =	con.prepareStatement(selectSchoolsSql);
     	ResultSet rs = ps.executeQuery();		
        facutlyDataTable.setModel(DbUtils.resultSetToTableModel(rs));
                rs.close();
                ps.close();
                con.close();
    }

    public JButton getAddFacultyButton() {
        return addFacultyButton;
    }

    public JTextField getDaysToTeach() {
        return daysToTeach;
    }

    public JTextField getDegree() {
        return degree;
    }

    public JButton getDeleteFacultyButton() {
        return deleteFacultyButton;
    }

    public JTable getFacutlyDataTable() {
        return facutlyDataTable;
    }

    public JTextField getFirstName() {
        return firstName;
    }

    public JTextField getGradSchool() {
        return gradSchool;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JTextField getLastName() {
        return lastName;
    }

    public JLabel getLblDaysToTeach() {
        return lblDaysToTeach;
    }

    public JLabel getLblDegree() {
        return lblDegree;
    }

    public JLabel getLblFirstName() {
        return lblFirstName;
    }

    public JLabel getLblGradSchool() {
        return lblGradSchool;
    }

    public JLabel getLblLastName() {
        return lblLastName;
    }

    public JLabel getLblMaxLoadFall() {
        return lblMaxLoadFall;
    }

    public JLabel getLblMaxLoadSpring() {
        return lblMaxLoadSpring;
    }

    public JLabel getLblMaxLoadSummer() {
        return lblMaxLoadSummer;
    }

    public JLabel getLblTitle() {
        return lblTitle;
    }

    public JTextField getMaxLoadFall() {
        return maxLoadFall;
    }

    public JTextField getMaxLoadSpring() {
        return maxLoadSpring;
    }

    public JTextField getMaxLoadSummer() {
        return maxLoadSummer;
    }

    

    public JButton getUpdateFacultyButton() {
        return updateFacultyButton;
    }

    

    public JLabel getFacultyMsgLabel() {
        return facultyMsgLabel;
    }

    public JTextField getTitleTextField() {
        return titleTextField;
    }

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFacultyButton;
    private javax.swing.JButton cancelFacultyButton;
    private javax.swing.JTextField daysToTeach;
    private javax.swing.JTextField degree;
    private javax.swing.JButton deleteFacultyButton;
    private javax.swing.JLabel facultyMsgLabel;
    private javax.swing.JTable facutlyDataTable;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextField gradSchool;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastName;
    private javax.swing.JLabel lblDaysToTeach;
    private javax.swing.JLabel lblDegree;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGradSchool;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMaxLoadFall;
    private javax.swing.JLabel lblMaxLoadSpring;
    private javax.swing.JLabel lblMaxLoadSummer;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField maxLoadFall;
    private javax.swing.JTextField maxLoadSpring;
    private javax.swing.JTextField maxLoadSummer;
    private javax.swing.JTextField titleTextField;
    private javax.swing.JButton updateFacultyButton;
    // End of variables declaration//GEN-END:variables
}
