/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mainframe;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

import net.proteanit.sql.DbUtils;

import org.mainframe.common.model.DBUtil;
import java.io.FileWriter;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author V
 */
public class GenerateScheduleFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserJInternalFrame
     */
    public GenerateScheduleFrame() {
        initComponents();
          getContentPane().setBackground(Color.WHITE);
        try{
            String sql = " Select DISTINCT Term From StudentCourse";
            Connection con = DBUtil.getDataSource().getConnection();
		PreparedStatement ps =	con.prepareStatement(sql);
		ResultSet rs = ps.executeQuery();
               semester.addItem("All");
                while(rs.next()){
                   semester.addItem(rs.getString(1));
                }
               
                rs.close();
                ps.close();
                con.close();
        }catch(Exception exp){
            JOptionPane.showMessageDialog(this, "exception raised"+exp);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generateSchedule = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        generateScheduleDataTable = new javax.swing.JTable();
        lblSemester = new javax.swing.JLabel();
        semester = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("GenerateScheduleFrame");

        generateSchedule.setBackground(new java.awt.Color(102, 255, 255));
        generateSchedule.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        generateSchedule.setText("Generate");
        generateSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateScheduleActionPerformed(evt);
            }
        });

        generateScheduleDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        generateScheduleDataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generateScheduleDataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(generateScheduleDataTable);

        lblSemester.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblSemester.setText("Semester");

        semester.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        semester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addComponent(generateSchedule))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(260, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateScheduleActionPerformed
        // TODO add your handling code here:
       try{
           
         loadDataIntoJTable();
       }catch(Exception exp){
           JOptionPane.showMessageDialog(null, exp);
       } 
        
    }//GEN-LAST:event_generateScheduleActionPerformed

    private void generateScheduleDataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateScheduleDataTableMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_generateScheduleDataTableMouseClicked

    private void semesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semesterActionPerformed

   
 
    
    public void loadDataIntoJTable() throws Exception{
    	
    	Connection con = DBUtil.getDataSource().getConnection();	
        String selescheduleSql = "Select Distinct crs.CourseCode , crs.CourseCap Capacity,crs.Teachers Faculty , s.SectionNumber Section , rm.RoomNumber , sem.semester Semester , sem.startDate , sem.EndDate From StudentCourse  stcrs , Course  crs , Semester sem,CourseSection s ,Room rm  Where stcrs.CourseID = crs.CourseCode and stcrs.CourseID=s.COURSE  and stcrs.term = sem.semester and rm.CourseCode = crs.CourseCode  ";
               
        if(semester.getSelectedItem()!= null  && !semester.getSelectedItem().equals("") && !semester.getSelectedItem().equals("All")){
            selescheduleSql = selescheduleSql + " and stcrs.Term = '"+semester.getSelectedItem()+"'";
        }
         selescheduleSql = selescheduleSql + " Order By crs.CourseCode ASC ";
        System.out.println("*******selescheduleSql "+selescheduleSql);
     	PreparedStatement ps =	con.prepareStatement(selescheduleSql);
     	ResultSet rs = ps.executeQuery();		
       
         generateScheduleDataTable.setModel(DbUtils.resultSetToTableModel(rs));
         
         StringBuffer sbTableData = new StringBuffer();
    for(int row = 0; row < generateScheduleDataTable.getRowCount(); row ++){
    for(int column = 0; column < generateScheduleDataTable.getColumnCount(); column ++){
        sbTableData.append(generateScheduleDataTable.getValueAt(row, column).toString().replace(",", " - ")).append(",");
    }
    sbTableData.append("\n");
}
         
        FileWriter fout = new FileWriter("d:/PhaniRajReport.csv");
        fout.write("CourseCode,Capacity,Faculty,Section,RoomNumber,Semester,StartDate,EndDate,\n");
        fout.write(sbTableData.toString());        
        fout.flush();
        fout.close();
                rs.close();
                ps.close();
                con.close();
                
        
    }

  

    public JButton getGenerateSchedule() {
        return generateSchedule;
    }

    public JTable getGenerateScheduleDataTable() {
        return generateScheduleDataTable;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JLabel getLblSemester() {
        return lblSemester;
    }
    public JComboBox<String> getSemester() {
        return semester;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateSchedule;
    private javax.swing.JTable generateScheduleDataTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JComboBox<String> semester;
    // End of variables declaration//GEN-END:variables
}
