/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mainframe;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

import net.proteanit.sql.DbUtils;

import org.mainframe.common.model.DBUtil;
import org.mainframe.common.model.GradSchoolModel;
import org.mainframe.common.bean.SchoolBean;
import javax.swing.JButton;

/**
 *
 * @author V
 */
public class GradSchoolFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserJInternalFrame
     */
    public GradSchoolFrame() {
        initComponents();
        schoolMsgLabel.setVisible(false);
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        schoolAbbrv = new javax.swing.JTextField();
        addSchoolButton = new javax.swing.JButton();
        updateSchoolButton = new javax.swing.JButton();
        deleteSchoolButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradSchoolDataTable = new javax.swing.JTable();
        schoolMsgLabel = new javax.swing.JLabel();
        cancelSchoolButton = new javax.swing.JButton();
        schoolName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("GraduateSchoolFrame");

        lblUsername.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblUsername.setText("GradSchool ");

        lblPassword.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblPassword.setText("GradSchoolName");

        addSchoolButton.setBackground(new java.awt.Color(102, 255, 255));
        addSchoolButton.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        addSchoolButton.setText("Add");
        addSchoolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSchoolButtonActionPerformed(evt);
            }
        });

        updateSchoolButton.setBackground(new java.awt.Color(102, 255, 255));
        updateSchoolButton.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        updateSchoolButton.setText("Update");
        updateSchoolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSchoolButtonActionPerformed(evt);
            }
        });

        deleteSchoolButton.setBackground(new java.awt.Color(102, 255, 255));
        deleteSchoolButton.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        deleteSchoolButton.setText("Delete");
        deleteSchoolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSchoolButtonActionPerformed(evt);
            }
        });

        gradSchoolDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        gradSchoolDataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradSchoolDataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gradSchoolDataTable);

        schoolMsgLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        schoolMsgLabel.setForeground(new java.awt.Color(255, 0, 0));

        cancelSchoolButton.setBackground(new java.awt.Color(102, 255, 255));
        cancelSchoolButton.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        cancelSchoolButton.setText("Reset");
        cancelSchoolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelSchoolButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(schoolAbbrv, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(schoolName)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(addSchoolButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(updateSchoolButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteSchoolButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelSchoolButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(schoolMsgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(schoolMsgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(schoolAbbrv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(schoolName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addSchoolButton)
                            .addComponent(updateSchoolButton)
                            .addComponent(deleteSchoolButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelSchoolButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addSchoolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSchoolButtonActionPerformed
        // TODO add your handling code here:
       try{
           
           if(schoolAbbrv.getText() !=null && !schoolAbbrv.getText().trim().equals("")){           
           
               if(new GradSchoolModel().getSchoolByAbbrev(schoolAbbrv.getText()) == null){
           SchoolBean schoolBean = new SchoolBean();
           schoolBean.setSchoolAbbrv(schoolAbbrv.getText());
           schoolBean.setSchoolName(schoolName.getText());
           new GradSchoolModel().addSchool(schoolBean);
           schoolMsgLabel.setText("Registration is Successfull.");           
           loadDataIntoJTable();                      
            schoolAbbrv.setText("");
            schoolName.setText("");
               }else{
                 schoolMsgLabel.setText("The given School Abbrevation is already existed.");  
               }
           }else{
               schoolMsgLabel.setText("School Abbrevation Should not be Empty.");
           }
       }catch(Exception exp){
           JOptionPane.showMessageDialog(null, exp);
       } 
        
    }//GEN-LAST:event_addSchoolButtonActionPerformed

    private void gradSchoolDataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradSchoolDataTableMouseClicked
        // TODO add your handling code here:
       try{
          int rowIndex = gradSchoolDataTable.getSelectedRow();
          
           schoolAbbrv.setText(gradSchoolDataTable.getValueAt(rowIndex, 0).toString());
           schoolName.setText(gradSchoolDataTable.getValueAt(rowIndex, 1).toString());          
       }catch(Exception exp){
           //JOptionPane.showMessageDialog(null, exp);
       }
    }//GEN-LAST:event_gradSchoolDataTableMouseClicked

    private void updateSchoolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSchoolButtonActionPerformed
        // TODO add your handling code here:
         try{
           if(new GradSchoolModel().getSchoolByAbbrev(schoolAbbrv.getText()) != null){
           SchoolBean schoolBean = new SchoolBean();
           schoolBean.setSchoolAbbrv(schoolAbbrv.getText());
           schoolBean.setSchoolName(schoolName.getText());
           new GradSchoolModel().updateSchool(schoolBean);
           
          loadDataIntoJTable();          
           
           schoolMsgLabel.setText("Updation is Successfull.");
         }else{
                 schoolMsgLabel.setText("Please enter valid School Abbrevation..!");
              }
       }catch(Exception exp){
           JOptionPane.showMessageDialog(null, exp);
       } 
    }//GEN-LAST:event_updateSchoolButtonActionPerformed

    private void deleteSchoolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSchoolButtonActionPerformed
        // TODO add your handling code here:
         try{
           SchoolBean schoolBean = new GradSchoolModel().getSchoolByAbbrev(schoolAbbrv.getText());
           if(schoolBean != null){
               new GradSchoolModel().deleteSchool(schoolAbbrv.getText());
               
               loadDataIntoJTable();
                
                schoolMsgLabel.setText("Deletion is Successfull.");
                schoolAbbrv.setText("");
                schoolName.setText("");
           }else{
           schoolMsgLabel.setText(" Please enter valid School Abbrevation .");
           }
       }catch(Exception exp){
           JOptionPane.showMessageDialog(null, exp);
       } 
    }//GEN-LAST:event_deleteSchoolButtonActionPerformed

    private void cancelSchoolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelSchoolButtonActionPerformed
        // TODO add your handling code here:
        schoolAbbrv.setText("");
        schoolName.setText("");
    }//GEN-LAST:event_cancelSchoolButtonActionPerformed

    public JTable getSchoolDataTable(){
        return gradSchoolDataTable;
    }
    
    public JLabel getSchoolMsgLabel(){
        return schoolMsgLabel;
    }
    
    public void loadDataIntoJTable() throws Exception{
    	
    	Connection con = DBUtil.getDataSource().getConnection();	
        String selectSchoolsSql = "Select * From GradSchool";
     	PreparedStatement ps =	con.prepareStatement(selectSchoolsSql);
     	ResultSet rs = ps.executeQuery();		
        gradSchoolDataTable.setModel(DbUtils.resultSetToTableModel(rs));
                rs.close();
                ps.close();
                con.close();
    }

    public JButton getAddSchoolButton() {
        return addSchoolButton;
    }

    public JButton getDeleteSchoolButton() {
        return deleteSchoolButton;
    }

    public JButton getUpdateSchoolButton() {
        return updateSchoolButton;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSchoolButton;
    private javax.swing.JButton cancelSchoolButton;
    private javax.swing.JButton deleteSchoolButton;
    private javax.swing.JTable gradSchoolDataTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField schoolAbbrv;
    private javax.swing.JLabel schoolMsgLabel;
    private javax.swing.JTextField schoolName;
    private javax.swing.JButton updateSchoolButton;
    // End of variables declaration//GEN-END:variables
}
