/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mainframe;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

import net.proteanit.sql.DbUtils;

import org.mainframe.common.model.DBUtil;
import org.mainframe.common.model.SemesterModel;
import org.mainframe.common.bean.SemesterBean;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author V
 */
public class SemesterFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserJInternalFrame
     */
    public SemesterFrame() {
        initComponents();
        semesterMsgLabel.setVisible(false);
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSemester = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        semester = new javax.swing.JTextField();
        addSemesterButton = new javax.swing.JButton();
        updateSemesterButton = new javax.swing.JButton();
        deleteSemesterButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        semesterDataTable = new javax.swing.JTable();
        semesterMsgLabel = new javax.swing.JLabel();
        endDate = new javax.swing.JTextField();
        lblEndDate = new javax.swing.JLabel();
        startDate = new javax.swing.JTextField();
        cancelSemesterButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("SemesterInternalFrame");

        lblSemester.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblSemester.setText("Semester");

        lblStartDate.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblStartDate.setText("Start Date");

        addSemesterButton.setBackground(new java.awt.Color(102, 255, 255));
        addSemesterButton.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        addSemesterButton.setText("Add");
        addSemesterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSemesterButtonActionPerformed(evt);
            }
        });

        updateSemesterButton.setBackground(new java.awt.Color(102, 255, 255));
        updateSemesterButton.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        updateSemesterButton.setText("Update");
        updateSemesterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSemesterButtonActionPerformed(evt);
            }
        });

        deleteSemesterButton.setBackground(new java.awt.Color(102, 255, 255));
        deleteSemesterButton.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        deleteSemesterButton.setText("Delete");
        deleteSemesterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSemesterButtonActionPerformed(evt);
            }
        });

        semesterDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        semesterDataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                semesterDataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(semesterDataTable);

        semesterMsgLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        semesterMsgLabel.setForeground(new java.awt.Color(255, 0, 0));

        lblEndDate.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblEndDate.setText("End Date");

        cancelSemesterButton.setBackground(new java.awt.Color(102, 255, 255));
        cancelSemesterButton.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        cancelSemesterButton.setText("Reset");
        cancelSemesterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelSemesterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSemester, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addSemesterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(updateSemesterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteSemesterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelSemesterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(80, 80, 80)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(semesterMsgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(semesterMsgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addSemesterButton)
                            .addComponent(updateSemesterButton)
                            .addComponent(deleteSemesterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelSemesterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addSemesterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSemesterButtonActionPerformed
        // TODO add your handling code here:
       try{
           
           if(semester.getText() !=null && !semester.getText().trim().equals("") ){    
                       
               SemesterModel semesterModel = new SemesterModel();
               SemesterBean semesterBean = new SemesterBean();
               semesterBean.setSemester(semester.getText());
               semesterBean.setStartDate(startDate.getText());
               semesterBean.setEndDate(endDate.getText());
               semesterModel.addSemester(semesterBean);
           semesterMsgLabel.setText("Registration is Successfull.");           
           loadDataIntoJTable();                      
            semester.setText("");
            startDate.setText("");
            endDate.setText("");
            
           }else{
               semesterMsgLabel.setText("Semester Should not be Empty.");
           }
       }catch(Exception exp){
           JOptionPane.showMessageDialog(null, exp);
       } 
        
    }//GEN-LAST:event_addSemesterButtonActionPerformed

    private void semesterDataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_semesterDataTableMouseClicked
        // TODO add your handling code here:
       try{
          int rowIndex = semesterDataTable.getSelectedRow();
          
           semester.setText(semesterDataTable.getValueAt(rowIndex, 0).toString());
           startDate.setText(semesterDataTable.getValueAt(rowIndex, 1).toString());          
           endDate.setText(semesterDataTable.getValueAt(rowIndex, 2).toString());          
                 
       }catch(Exception exp){
           //JOptionPane.showMessageDialog(null, exp);
       }
    }//GEN-LAST:event_semesterDataTableMouseClicked

    private void updateSemesterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSemesterButtonActionPerformed
        // TODO add your handling code here:
        try{
           
           if(semester.getText() !=null && !semester.getText().trim().equals("") ){    
                      
               SemesterModel semesterModel = new SemesterModel();
                if(semesterModel.isSemesterExist(semester.getText())){
               SemesterBean semesterBean = new SemesterBean();
               semesterBean.setSemester(semester.getText());
               semesterBean.setStartDate(startDate.getText());
               semesterBean.setEndDate(endDate.getText());
               semesterModel.updateSemester(semesterBean);
           semesterMsgLabel.setText("Updation is Successfull.");           
           loadDataIntoJTable();                      
                        
           }else{
               semesterMsgLabel.setText("Semester does not exist.");
           }
           }else{
               semesterMsgLabel.setText("Semester Should not be Empty.");
           }
       }catch(Exception exp){
           JOptionPane.showMessageDialog(null, exp);
       } 
        
    }//GEN-LAST:event_updateSemesterButtonActionPerformed

    private void deleteSemesterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSemesterButtonActionPerformed
        // TODO add your handling code here:
        try{
           
           if(semester.getText() !=null && !semester.getText().trim().equals("") ){    
                       
           SemesterModel semesterModel = new SemesterModel();
         boolean flag =  semesterModel.deleteSemester(semester.getText());
         if(flag){
           semesterMsgLabel.setText("Deletion is Successfull.");        
         }else{
             semesterMsgLabel.setText("Semester does not exist.");
         }
           loadDataIntoJTable();                      
            semester.setText("");
            startDate.setText("");
            endDate.setText("");
            
           }else{
               semesterMsgLabel.setText("Semester Should not be Empty.");
           }
       }catch(Exception exp){
           JOptionPane.showMessageDialog(null, exp);
       } 
        
    }//GEN-LAST:event_deleteSemesterButtonActionPerformed

    private void cancelSemesterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelSemesterButtonActionPerformed
        // TODO add your handling code here:
            semester.setText("");
            startDate.setText("");
            endDate.setText("");
          
    }//GEN-LAST:event_cancelSemesterButtonActionPerformed

    
    
    public void loadDataIntoJTable() throws Exception{
    	
    	Connection con = DBUtil.getDataSource().getConnection();	
        String selectSchoolsSql = "Select * From Semester";
     	PreparedStatement ps =	con.prepareStatement(selectSchoolsSql);
     	ResultSet rs = ps.executeQuery();		
        semesterDataTable.setModel(DbUtils.resultSetToTableModel(rs));
                rs.close();
                ps.close();
                con.close();
    }

    public JButton getAddSemesterButton() {
        return addSemesterButton;
    }

    public JButton getCancelSemesterButton() {
        return cancelSemesterButton;
    }

    public JButton getDeleteSemesterButton() {
        return deleteSemesterButton;
    }

    public JTextField getEndDate() {
        return endDate;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JLabel getLblEndDate() {
        return lblEndDate;
    }

    public JLabel getLblSemester() {
        return lblSemester;
    }

    public JLabel getLblStartDate() {
        return lblStartDate;
    }

    public JTextField getSemester() {
        return semester;
    }

    public JTable getSemesterDataTable() {
        return semesterDataTable;
    }

    public JLabel getSemesterMsgLabel() {
        return semesterMsgLabel;
    }

    public JTextField getStartDate() {
        return startDate;
    }

    public JButton getUpdateSemesterButton() {
        return updateSemesterButton;
    }
  
     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSemesterButton;
    private javax.swing.JButton cancelSemesterButton;
    private javax.swing.JButton deleteSemesterButton;
    private javax.swing.JTextField endDate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEndDate;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JTextField semester;
    private javax.swing.JTable semesterDataTable;
    private javax.swing.JLabel semesterMsgLabel;
    private javax.swing.JTextField startDate;
    private javax.swing.JButton updateSemesterButton;
    // End of variables declaration//GEN-END:variables
}
