/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mainframe;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

import net.proteanit.sql.DbUtils;

import org.mainframe.common.model.DBUtil;
import org.mainframe.common.model.StudentModel;
import org.mainframe.common.bean.StudentBean;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author V
 */
public class StudentFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserJInternalFrame
     */
    public StudentFrame() {
        initComponents();
        studentMsgLabel.setVisible(false);
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStudentId = new javax.swing.JLabel();
        lblDegreeCode = new javax.swing.JLabel();
        studentId = new javax.swing.JTextField();
        addStudentButton = new javax.swing.JButton();
        updateStudentButton = new javax.swing.JButton();
        deleteStudentButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentDataTable = new javax.swing.JTable();
        studentMsgLabel = new javax.swing.JLabel();
        graduationTerm = new javax.swing.JTextField();
        lblGraduationTerm = new javax.swing.JLabel();
        degreeCode = new javax.swing.JTextField();
        cancelStudentButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("StudentFrame");

        lblStudentId.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblStudentId.setText("Student ID");

        lblDegreeCode.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblDegreeCode.setText("Degree Code");

        addStudentButton.setBackground(new java.awt.Color(102, 255, 255));
        addStudentButton.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        addStudentButton.setText("Add");
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });

        updateStudentButton.setBackground(new java.awt.Color(102, 255, 255));
        updateStudentButton.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        updateStudentButton.setText("Update");
        updateStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStudentButtonActionPerformed(evt);
            }
        });

        deleteStudentButton.setBackground(new java.awt.Color(102, 255, 255));
        deleteStudentButton.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        deleteStudentButton.setText("Delete");
        deleteStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentButtonActionPerformed(evt);
            }
        });

        studentDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        studentDataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentDataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studentDataTable);

        studentMsgLabel.setBackground(new java.awt.Color(255, 255, 255));
        studentMsgLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        studentMsgLabel.setForeground(new java.awt.Color(255, 0, 0));

        lblGraduationTerm.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblGraduationTerm.setText("Graduation Term");

        cancelStudentButton.setBackground(new java.awt.Color(102, 255, 255));
        cancelStudentButton.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        cancelStudentButton.setText("Reset");
        cancelStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelStudentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDegreeCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblStudentId, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(studentId, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(degreeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblGraduationTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(graduationTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(updateStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(studentMsgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(studentMsgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDegreeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(degreeCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGraduationTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(graduationTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addStudentButton)
                            .addComponent(updateStudentButton)
                            .addComponent(deleteStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
        // TODO add your handling code here:
       try{
           
           if(studentId.getText() !=null && !studentId.getText().trim().equals("") ){    
                       
               StudentModel studentModel = new StudentModel();
               StudentBean studentBean = new StudentBean();
               studentBean.setStudentId(studentId.getText());
               studentBean.setDegreeCode(degreeCode.getText());
               studentBean.setGraduationDate(graduationTerm.getText());
               studentModel.addStudent(studentBean);
           studentMsgLabel.setText("Registration is Successfull.");           
           loadDataIntoJTable();                      
            studentId.setText("");
            degreeCode.setText("");
            graduationTerm.setText("");
            
           }else{
               studentMsgLabel.setText("StudentID Should not be Empty.");
           }
       }catch(Exception exp){
           JOptionPane.showMessageDialog(null, exp);
       } 
        
    }//GEN-LAST:event_addStudentButtonActionPerformed

    private void studentDataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentDataTableMouseClicked
        // TODO add your handling code here:
       try{
          int rowIndex = studentDataTable.getSelectedRow();
          
           studentId.setText(studentDataTable.getValueAt(rowIndex, 0).toString());
           degreeCode.setText(studentDataTable.getValueAt(rowIndex, 1).toString());          
           graduationTerm.setText(studentDataTable.getValueAt(rowIndex, 2).toString());          
                 
       }catch(Exception exp){
           //JOptionPane.showMessageDialog(null, exp);
       }
    }//GEN-LAST:event_studentDataTableMouseClicked

    private void updateStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStudentButtonActionPerformed
        // TODO add your handling code here:
        try{
           
           if(studentId.getText() !=null && !studentId.getText().trim().equals("") ){    
                      
               StudentModel studentModel = new StudentModel();
                if(studentModel.isStudentExist(studentId.getText())){
               StudentBean studentBean = new StudentBean();
               studentBean.setStudentId(studentId.getText());
               studentBean.setDegreeCode(degreeCode.getText());
               studentBean.setGraduationDate(graduationTerm.getText());
               studentModel.updateStudent(studentBean);
           studentMsgLabel.setText("Updation is Successfull.");           
           loadDataIntoJTable();                      
                        
           }else{
               studentMsgLabel.setText("StudentID does not exist.");
           }
           }else{
               studentMsgLabel.setText("StudentID Should not be Empty.");
           }
       }catch(Exception exp){
           JOptionPane.showMessageDialog(null, exp);
       } 
        
    }//GEN-LAST:event_updateStudentButtonActionPerformed

    private void deleteStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentButtonActionPerformed
        // TODO add your handling code here:
        try{
           
           if(studentId.getText() !=null && !studentId.getText().trim().equals("") ){    
                       
           StudentModel studentModel = new StudentModel();
         boolean flag =  studentModel.deleteStudent(studentId.getText());
         if(flag){
           studentMsgLabel.setText("Deletion is Successfull.");        
         }else{
             studentMsgLabel.setText("Student id does not exist.");
         }
           loadDataIntoJTable();                      
            studentId.setText("");
            degreeCode.setText("");
            graduationTerm.setText("");
            
           }else{
               studentMsgLabel.setText("StudentID Should not be Empty.");
           }
       }catch(Exception exp){
           JOptionPane.showMessageDialog(null, exp);
       } 
        
    }//GEN-LAST:event_deleteStudentButtonActionPerformed

    private void cancelStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelStudentButtonActionPerformed
        // TODO add your handling code here:
            studentId.setText("");
            degreeCode.setText("");
            graduationTerm.setText("");
          
    }//GEN-LAST:event_cancelStudentButtonActionPerformed

    public JTable getSchoolDataTable(){
        return studentDataTable;
    }
    
    public JLabel getSchoolMsgLabel(){
        return studentMsgLabel;
    }
    
    public void loadDataIntoJTable() throws Exception{
    	
    	Connection con = DBUtil.getDataSource().getConnection();	
        String selectSchoolsSql = "Select * From Student";
     	PreparedStatement ps =	con.prepareStatement(selectSchoolsSql);
     	ResultSet rs = ps.executeQuery();		
        studentDataTable.setModel(DbUtils.resultSetToTableModel(rs));
                rs.close();
                ps.close();
                con.close();
    }

    public JButton getAddStudentButton() {
        return addStudentButton;
    }

    public JButton getCancelStudentButton() {
        return cancelStudentButton;
    }

    public JTextField getDegreeCode() {
        return degreeCode;
    }

    public JButton getDeleteStudentButton() {
        return deleteStudentButton;
    }

    public JTextField getGraduationTerm() {
        return graduationTerm;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JLabel getLblDegreeCode() {
        return lblDegreeCode;
    }

    public JLabel getLblGraduationTerm() {
        return lblGraduationTerm;
    }

    public JLabel getLblStudentName() {
        return lblStudentId;
    }

    public JTable getStudentDataTable() {
        return studentDataTable;
    }

    public JTextField getStudentId() {
        return studentId;
    }

    public JLabel getStudentMsgLabel() {
        return studentMsgLabel;
    }

    public JButton getUpdateStudentButton() {
        return updateStudentButton;
    }

    public JLabel getLblStudentId() {
        return lblStudentId;
    }
    

     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStudentButton;
    private javax.swing.JButton cancelStudentButton;
    private javax.swing.JTextField degreeCode;
    private javax.swing.JButton deleteStudentButton;
    private javax.swing.JTextField graduationTerm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDegreeCode;
    private javax.swing.JLabel lblGraduationTerm;
    private javax.swing.JLabel lblStudentId;
    private javax.swing.JTable studentDataTable;
    private javax.swing.JTextField studentId;
    private javax.swing.JLabel studentMsgLabel;
    private javax.swing.JButton updateStudentButton;
    // End of variables declaration//GEN-END:variables
}
