/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mainframe;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

import net.proteanit.sql.DbUtils;

import org.mainframe.common.model.DBUtil;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author V
 */
public class StudentReportFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserJInternalFrame
     */
    public StudentReportFrame() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        try{
            String sql = " Select DISTINCT Term From StudentCourse Order By Term DESC";
            Connection con = DBUtil.getDataSource().getConnection();
		PreparedStatement ps =	con.prepareStatement(sql);
		ResultSet rs = ps.executeQuery();
               //semester.addItem("All");
                while(rs.next()){
                   semester.addItem(rs.getString(1));
                }
               
                rs.close();
                ps.close();
                con.close();
        }catch(Exception exp){
            JOptionPane.showMessageDialog(this, "exception raised"+exp);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generateSchedule = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentReportDataTable = new javax.swing.JTable();
        lblSemester = new javax.swing.JLabel();
        semester = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("ScheduleReportFrame");

        generateSchedule.setBackground(new java.awt.Color(102, 255, 255));
        generateSchedule.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        generateSchedule.setText("getReport");
        generateSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateScheduleActionPerformed(evt);
            }
        });

        studentReportDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        studentReportDataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentReportDataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studentReportDataTable);

        lblSemester.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblSemester.setText("Semester");

        semester.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        semester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(484, 484, 484))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(generateSchedule))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(300, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateScheduleActionPerformed
        // TODO add your handling code here:
       try{
           
         loadDataIntoJTable();
       }catch(Exception exp){
           JOptionPane.showMessageDialog(null, exp);
       } 
        
    }//GEN-LAST:event_generateScheduleActionPerformed

    private void studentReportDataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentReportDataTableMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_studentReportDataTableMouseClicked

    private void semesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semesterActionPerformed

   
 
    
    public void loadDataIntoJTable() throws Exception{
    	
    	Connection con = DBUtil.getDataSource().getConnection();	
        String selescheduleSql = "Select StudentID , count(CourseId) completed, 3 - count(CourseId) Needs_To_complete From StudentCourse  ";
               
        if(semester.getSelectedItem()!= null  && !semester.getSelectedItem().equals("") ){
            selescheduleSql = selescheduleSql + " Where term = '"+semester.getSelectedItem()+"'";
        }
         selescheduleSql = selescheduleSql + " Group By StudentID HAVING count(CourseId) <= 3 ";
        System.out.println("*******selescheduleSql "+selescheduleSql);
     	PreparedStatement ps =	con.prepareStatement(selescheduleSql);
     	ResultSet rs = ps.executeQuery();		
        studentReportDataTable.setModel(DbUtils.resultSetToTableModel(rs));
                rs.close();
                ps.close();
                con.close();
                
       
    }

    public JButton getGenerateSchedule() {
        return generateSchedule;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JLabel getLblSemester() {
        return lblSemester;
    }

    public JComboBox<String> getSemester() {
        return semester;
    }

    public JTable getStudentReportDataTable() {
        return studentReportDataTable;
    }

          
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateSchedule;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JComboBox<String> semester;
    private javax.swing.JTable studentReportDataTable;
    // End of variables declaration//GEN-END:variables
}
