/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mainframe;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

import net.proteanit.sql.DbUtils;

import org.mainframe.common.model.DBUtil;
import org.mainframe.common.model.ReportsModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author V
 */
public class TestScheduleFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserJInternalFrame
     */
    public TestScheduleFrame() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        try{
            String sql = " Select DISTINCT Term From StudentCourse Order By Term DESC";
            Connection con = DBUtil.getDataSource().getConnection();
		PreparedStatement ps =	con.prepareStatement(sql);
		ResultSet rs = ps.executeQuery();
             //  semester.addItem("All");
                while(rs.next()){
                   semester.addItem(rs.getString(1));
                }
               
                rs.close();
                ps.close();
                con.close();
        }catch(Exception exp){
            JOptionPane.showMessageDialog(this, "exception raised"+exp);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        testSchedule = new javax.swing.JButton();
        lblSemester = new javax.swing.JLabel();
        semester = new javax.swing.JComboBox<>();
        lblNumberOfStudent = new javax.swing.JLabel();
        lblWithoutRequiredStudentsCourses = new javax.swing.JLabel();
        lblRequiredStudentsCourses = new javax.swing.JLabel();
        lblNoOfSectionsWithTolerance = new javax.swing.JLabel();
        lblNoOfSections = new javax.swing.JLabel();
        lblNoOfSectionsBelowPercent = new javax.swing.JLabel();
        lblNoOfSectionsAboveCap1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("TestScheduleFrame");

        testSchedule.setBackground(new java.awt.Color(102, 255, 255));
        testSchedule.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        testSchedule.setText("Test");
        testSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testScheduleActionPerformed(evt);
            }
        });

        lblSemester.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblSemester.setText("Select Semester");

        semester.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        semester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterActionPerformed(evt);
            }
        });

        lblNumberOfStudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblWithoutRequiredStudentsCourses.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblRequiredStudentsCourses.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblNoOfSectionsWithTolerance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblNoOfSections.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblNoOfSectionsBelowPercent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblNoOfSectionsAboveCap1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(testSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRequiredStudentsCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumberOfStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNoOfSections, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWithoutRequiredStudentsCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNoOfSectionsWithTolerance, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNoOfSectionsBelowPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNoOfSectionsAboveCap1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(410, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNumberOfStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testSchedule)
                    .addComponent(lblRequiredStudentsCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblWithoutRequiredStudentsCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNoOfSections, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNoOfSectionsWithTolerance, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNoOfSectionsAboveCap1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(lblNoOfSectionsBelowPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testScheduleActionPerformed
        // TODO add your handling code here:
       try{
           ReportsModel reportsModel = new ReportsModel();
       
       Long countOfStudents =   reportsModel.getNumberOfStudents(semester.getSelectedItem().toString());
       lblNumberOfStudent.setText("Number of students   "+countOfStudents);
       
       Long countOfStudentReqCourses = reportsModel.getRequiredStudentCount(semester.getSelectedItem().toString());
       lblRequiredStudentsCourses.setText(" Number students  enrolled in core  courses "+countOfStudentReqCourses);
       
       //Long countOfStudentWithoutReqCourses = reportsModel.getWithoutRequiredStudentCount(semester.getSelectedItem().toString());
       lblWithoutRequiredStudentsCourses.setText(" Number students not enrolled in core  courses "+(countOfStudents-countOfStudentReqCourses));
       
       Long countOfDegrees = reportsModel.getDegreesCountBySemester(semester.getSelectedItem().toString());
       
       lblNoOfSections.setText(" Number of Degrees "+countOfDegrees);     
             
       lblNoOfSectionsWithTolerance.setText("Number Of Faculty   "+reportsModel.getFacultyCountBySemester(semester.getSelectedItem().toString()));
      
       }catch(Exception exp){
         //  JOptionPane.showMessageDialog(null, exp);
       } 
        
    }//GEN-LAST:event_testScheduleActionPerformed

    private void semesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semesterActionPerformed

    public JLabel getLblNoOfSections1() {
        return lblNoOfSections;
    }

    public void setLblNoOfSections1(JLabel lblNoOfSections1) {
        this.lblNoOfSections = lblNoOfSections1;
    }

    public JLabel getLblNoOfSectionsAboveCap1() {
        return lblNoOfSectionsAboveCap1;
    }

    public void setLblNoOfSectionsAboveCap1(JLabel lblNoOfSectionsAboveCap1) {
        this.lblNoOfSectionsAboveCap1 = lblNoOfSectionsAboveCap1;
    }

    public JLabel getLblNoOfSectionsBelowPercent() {
        return lblNoOfSectionsBelowPercent;
    }

    public void setLblNoOfSectionsBelowPercent(JLabel lblNoOfSectionsBelowPercent) {
        this.lblNoOfSectionsBelowPercent = lblNoOfSectionsBelowPercent;
    }

    public JLabel getLblNoOfSectionsWithTolerance() {
        return lblNoOfSectionsWithTolerance;
    }

    public void setLblNoOfSectionsWithTolerance(JLabel lblNoOfSectionsWithTolerance) {
        this.lblNoOfSectionsWithTolerance = lblNoOfSectionsWithTolerance;
    }

    public JLabel getLblNumberOfStudent() {
        return lblNumberOfStudent;
    }

    public void setLblNumberOfStudent(JLabel lblNumberOfStudent) {
        this.lblNumberOfStudent = lblNumberOfStudent;
    }

    public JLabel getLblRequiredStudentsCourses1() {
        return lblRequiredStudentsCourses;
    }

    public void setLblRequiredStudentsCourses1(JLabel lblRequiredStudentsCourses1) {
        this.lblRequiredStudentsCourses = lblRequiredStudentsCourses1;
    }

    public JLabel getLblSemester() {
        return lblSemester;
    }

    public void setLblSemester(JLabel lblSemester) {
        this.lblSemester = lblSemester;
    }

    public JLabel getLblWithoutRequiredStudentsCourses() {
        return lblWithoutRequiredStudentsCourses;
    }

    public void setLblWithoutRequiredStudentsCourses(JLabel lblWithoutRequiredStudentsCourses) {
        this.lblWithoutRequiredStudentsCourses = lblWithoutRequiredStudentsCourses;
    }

    public JComboBox<String> getSemester() {
        return semester;
    }

    public void setSemester(JComboBox<String> semester) {
        this.semester = semester;
    }

    public JButton getTestSchedule() {
        return testSchedule;
    }

    public void setTestSchedule(JButton testSchedule) {
        this.testSchedule = testSchedule;
    }

   
 
    
    
     
    
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNoOfSections;
    private javax.swing.JLabel lblNoOfSectionsAboveCap1;
    private javax.swing.JLabel lblNoOfSectionsBelowPercent;
    private javax.swing.JLabel lblNoOfSectionsWithTolerance;
    private javax.swing.JLabel lblNumberOfStudent;
    private javax.swing.JLabel lblRequiredStudentsCourses;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblWithoutRequiredStudentsCourses;
    private javax.swing.JComboBox<String> semester;
    private javax.swing.JButton testSchedule;
    // End of variables declaration//GEN-END:variables
}
